### ISSUE TITLE
NoIndexing option for >1500 bytes

### ISSUE THREAD

**Issue by david02871** [googleapis/nodejs-datastore-kvstore#5]
I found this package easy to setup and use until I tried to store some JSON which was over 1500 bytes.

{ [Error: The value of property "value" is longer than 1500 bytes.]
  code: 400,
  metadata: Metadata { _internal_repr: {} },
  message: 'The value of property "value" is longer than 1500 bytes.' }

This can be solved by setting "excludeFromIndexes" but gcloud-kvstore does not seem to provide that option?

**Comment by stephenplusplus** [comment]
Correct, there isn't a way to do this currently. What do you think a good API would look like to allow this?

**Comment by david02871** [comment]
Anything sent with over 1500 bytes could be sent with the excludeFromIndexes flag since it can not be indexed

**Comment by sofisl** [comment]
Hi there! Since this is an API (not client library) issue, I think it would be better to document the issue [here](https://cloud.google.com/support/docs/issue-trackers), under Datastore. Closing this for now since this library will be moved to [google-cloud-node](https://github.com/googleapis/google-cloud-node).
